### ISSUE TITLE
training parameters on Flickr30k dataset 

### ISSUE THREAD

**Issue by mzhaoshuai** [DavidHuji/CapDec#11]
Hi, thx for your wonderful work!

I am trying to reproduce the Flickr30k captioning experiments in Table 1 in the paper, however, using the default parameters `lr=2e-5` and `epoch=10`, I get a much worse performance.

Could you please share your training parameters on Flickr30k dataset ?

**Comment by DavidHuji** [comment]
Hi, thanks for the interest in our work. I think on Flickr it requires more epochs, we trained until the validation results started to get worse. For COCO it was about 8 epochs but for smaller datasets (i.e. FlickrStyle10k), it was about 25 epochs.

**Comment by mzhaoshuai** [comment]
Thx for your response 😄 !
